version: '3.8'
services:

  app:
    build:
      dockerfile: Dockerfile
      context: .
      tags:
        - "fabricioandreis/ports-app:latest"
    environment:
      - PORTS_INPUT_JSON_PATH=/data/ports.json
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=
    volumes:
      - ./ports.json:/data/ports.json
    depends_on:
      - redis

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --loglevel warning
    volumes:
      - redis:/data

  acceptance-tests:
    build:
      dockerfile: ./internal/tests/Dockerfile
      context: .
      tags:
        - "fabricioandreis/ports-app-accept-tests:latest"
    environment:
      - PORTS_INPUT_JSON_PATH=/data/ports.json
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=
    volumes:
      - ./internal/tests/subset-ports.json:/data/ports.json
    depends_on:
      app:
        condition: service_completed_successfully

volumes:
  redis:
    driver: local
