# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Continuous Delivery pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  continuous-delivery:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Static analysis
      run: make vet

    - name: Build
      run: make build

    - name: Test Coverage
      run: make test-coverage

    - name: Archive unit test results
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-results
        path: unit-test-results.json

    - name: Archive unit test coverage
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-coverage
        path: unit-test-coverage.html

    - name: Archive release candidate
      uses: actions/upload-artifact@v3
      with:
        name: release-candidate-binary
        path: ports-app

    - name: Run Acceptance Tests
      run: make acceptance-tests
    